### ISSUE TITLE
Issue when generating html docs from swagger file for vCenter 6.7

### ISSUE THREAD

**Issue by alanrenouf** [vmware/vmware-openapi-generator#15]
Just tried the latest version of the openapi generator against 6.7 VC and it created me a swagger file but when i try and use it with an off the shelf doc generator (redoc) for a swagger file i get the following error

```
SyntaxError: Error resolving $ref pointer "/Users/renoufa/Dropbox%20(VMware)/Github/vmw-redoc/vcenter.json#/definitions/com.vmware.cis.task.status".
Token "com.vmware.cis.task.status" does not exist.
    at Pointer.resolve (/Users/renoufa/.npm/_npx/55113/lib/node_modules/redoc-cli/node_modules/json-schema-ref-parser/lib/pointer.js:87:17)
    at $Ref.resolve (/Users/renoufa/.npm/_npx/55113/lib/node_modules/redoc-cli/node_modules/json-schema-ref-parser/lib/ref.js:83:18)
    at $Refs._resolve (/Users/renoufa/.npm/_npx/55113/lib/node_modules/redoc-cli/node_modules/json-schema-ref-parser/lib/refs.js:155:15)
    at inventory$Ref (/Users/renoufa/.npm/_npx/55113/lib/node_modules/redoc-cli/node_modules/json-schema-ref-parser/lib/bundle.js:99:23)
    at /Users/renoufa/.npm/_npx/55113/lib/node_modules/redoc-cli/node_modules/json-schema-ref-parser/lib/bundle.js:74:11
    at Array.forEach (<anonymous>)
    at crawl (/Users/renoufa/.npm/_npx/55113/lib/node_modules/redoc-cli/node_modules/json-schema-ref-parser/lib/bundle.js:68:12)
    at /Users/renoufa/.npm/_npx/55113/lib/node_modules/redoc-cli/node_modules/json-schema-ref-parser/lib/bundle.js:77:11
    at Array.forEach (<anonymous>)
```

**Comment by shashankkumar88** [comment]
Can anyone share the generated swagger file?

**Comment by kunal-pmj** [comment]
You can run the generator against your vcsa

**Comment by shashankkumar88** [comment]
> You can run the generator against your vcsa

Thanks. However I don't have a vcsa. Is there a free version of vcsa available?

**Comment by kunal-pmj** [comment]
https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.install.doc/GUID-11468F6F-0D8C-41B1-82C9-29284630A4FF.html
Follow the link.
